project:
  type: book

book:
  title: "Python Básico"
  image: mactiR.png
  author: "Luis Miguel de la Cruz Salas"
  date: "1/12/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - T01_Etiquetas_y_Palabras_Reservadas.ipynb
    - T02_Expr_Decla.ipynb
    - T03_TiposBasico_Operadores.ipynb
    - T04_Cadenas.ipynb
    - T05_Estructura_de_Datos.ipynb
    - T06_Control_de_flujo.ipynb
    - T07_Entrada_salida_estandar.ipynb
    - T08_Archivos_Gestores_de_contexto.ipynb
    - T09_Funciones_y_docstring.ipynb
    - T10_LambdaExpressions.ipynb
    - T11_Excepciones.ipynb
    - T12_IterablesMapFilterReduce.ipynb
    - T13_Comprehensions.ipynb
    - T14_IteradoresGeneradores.ipynb
    - T15_Decoradores.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



